#ifndef _STATBAR_H_
#define _STATBAR_H_

#define WC_STATBAR  ("App:HanEdit-Statbar")

#define STATBAR_USERM_SETHANMODE    (WM_USER+0)
#define STATBAR_USERM_SETMODIFIED   (WM_USER+1)
#define STATBAR_USERM_SETKBDTYPE    (WM_USER+2)
#define STATBAR_USERM_SETEOLTYPE    (WM_USER+3)
#define STATBAR_USERM_SETHANTYPE    (WM_USER+4)
#define STATBAR_USERM_SETLINECOL    (WM_USER+5)
#define STATBAR_USERM_SETINSERTMODE (WM_USER+6)

BOOL EXPENTRY RegisterStatbarControl(HAB hab);

#endif // _STATBAR_H_
